modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="pixelator"
version="1.2.1"
displayName="Pixelator"
displayURL="https://modrinth.com/mod/pixelator"
logoFile="logo.png"
credits="Created by firemariosXD"
authors="firemariosXD"
description="A mod based on lugis Mansion 2"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.pixelator]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration